name: Convert cn-domain-list to Mihomo format

on:
  push:
    branches:
      - 'rule-set'
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点执行一次，以同步上游更新
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'rule-set'

    - name: Download latest Mihomo binary
      run: |
        set -e # 如果任何命令失败，立即退出脚本
        
        # 从 GitHub API 获取最新的 release 信息，并精确筛选出 compatible 版本的 linux-amd64 压缩包
        MIHOMO_URL=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.assets[] | select(.name | test("mihomo-linux-amd64-compatible.*\\.gz$")) | .browser_download_url')
        
        # 检查是否成功获取到 URL
        if [ -z "$MIHOMO_URL" ]; then
          echo "Error: Could not find Mihomo compatible binary download URL."
          exit 1
        fi
        
        echo "Downloading Mihomo from: $MIHOMO_URL"
        
        # 下载文件
        curl -L -o mihomo.gz "$MIHOMO_URL"
        
        # 解压、赋予权限并移动到系统路径
        gunzip mihomo.gz
        chmod +x mihomo
        sudo mv mihomo /usr/local/bin/
        
        # 验证安装并显示版本号
        echo "Mihomo installed successfully:"
        mihomo -v

    - name: Process JSON and create YAML in Classic Format
      run: |
        set -e
        echo "payload:" > cn-domain-list.yaml
        echo "Processing domain suffixes..."
        jq -r '.rules[0].domain_suffix[]' ext-cn-list.json | while IFS= read -r suffix; do
          echo "  - DOMAIN-SUFFIX,${suffix#.}" >> cn-domain-list.yaml
        done
        echo "Processing domains..."
        jq -r '.rules[0].domain[]' ext-cn-list.json | while IFS= read -r domain; do
          echo "  - DOMAIN,${domain}" >> cn-domain-list.yaml
        done
        echo "Created cn-domain-list.yaml in classic format."

    - name: Convert to mrs format
      run: |
        # ！！！关键修正！！！
        # 即使 YAML 是 classic 格式，其行为也是 'domain'
        mihomo convert-ruleset domain yaml cn-domain-list.yaml cn-domain-list.mrs
        echo "Converted classic YAML to cn-domain-list.mrs"

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated update of Mihomo rule files (classic format)"
        branch: rule-set
        file_pattern: '*.yaml *.mrs'
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
        commit_author: GitHub Actions <actions@github.com>
