name: Convert Rules and Push to rule-set branch

# 触发器配置 (此文件在 main 分支)
on:
  # 允许在 Actions 页面手动触发 (将运行 main 分支的此 workflow)
  workflow_dispatch:

  # 每天定时执行 (也将运行 main 分支的此 workflow)
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-commit-to-ruleset:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 明确检出 'rule-set' 分支
      # 这是最关键的修改。工作流将在这个分支的内容上进行操作。
      - name: Checkout 'rule-set' branch
        uses: actions/checkout@v4
        with:
          # 指定要操作的分支名
          ref: 'rule-set'

      # 步骤 2: 检出源数据仓库 (这部分不变)
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: xmdhs/cn-domain-list
          ref: rule-set
          path: cn-domain-list-source

      # 步骤 3: 执行转换 (这部分不变)
      - name: Convert to various formats
        run: |
          SOURCE_JSON="cn-domain-list-source/ext-cn-list.json"
          # --- 生成 .mrs 文件 ---
          jq -r '.domain_suffix[] | "DOMAIN-SUFFIX," + .' $SOURCE_JSON > suffix.tmp
          jq -r '.domain[] | "DOMAIN," + .' $SOURCE_JSON > domain.tmp
          cat suffix.tmp domain.tmp > cn-list.mrs
          # --- 生成 Clash YAML 文件 ---
          echo "payload:" > cn-list.yaml
          jq -r '.domain_suffix[] | "  - '\''DOMAIN-SUFFIX," + . + "'\''"' $SOURCE_JSON >> cn-list.yaml
          jq -r '.domain[] | "  - '\''DOMAIN," + . + "'\''"' $SOURCE_JSON >> cn-list.yaml
          rm suffix.tmp domain.tmp

      # 步骤 4: 提交并推送到 'rule-set' 分支
      # 因为我们在步骤 1 已经检出了 'rule-set' 分支，
      # 所以这里的 git 命令会自动推送到 'rule-set'。
      - name: Commit and push files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cn-list.mrs cn-list.yaml
          if ! git diff --staged --quiet; then
            git commit -m "Update rule files"
            # git push 会自动推送到当前检出的分支，即 'rule-set'
            git push
            echo "Changes committed and pushed to rule-set branch."
          else
            echo "No changes to commit."
          fi
